layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: derahmedk
  # instagram: your_username
  # keybase: your_username
  linkedin: ahmed1krimi
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://isocpp.org/
    image_url: https://isocpp.org/assets/images/cpp_logo.png
  
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: PyTorch
    web_url: https://pytorch.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg
  
  - name: TensorFlow
    web_url: https://www.tensorflow.org/
    image_url: https://www.gstatic.com/devrel-devsite/prod/vdbb152dfd6ef5e309aa1d261d45f3fd443aed2691cbfba3f9f80f8a4012a0a8f/tensorflow/images/lockup.svg

  - name: ROS
    web_url: https://ros.org/
    image_url: https://www.ros.org/imgs/ros_logo.png
    
